### ISSUE TITLE
How to evaluate the status of the transanction?

### ISSUE THREAD

**Issue by kekavc24** [lazicah/flutterwave_web_client#1]
Hi, 
Found your awesome flutterwave package and it really works well for web. However, I'm unable to evaluate after the transaction was successful. It just prints the currency and country. What boolean does the response.status evaluate to?
![Screenshot (6)](https://user-images.githubusercontent.com/68240897/135532344-282b03dc-a0f1-4409-8bf8-1f322e5f68dc.png)

**Comment by lazicah** [comment]
Hi, thank you. Because this is based on the Flutterwave's inline payment, I can only return a checkout response for a successful transaction. If the transaction was successful, you should the response.status is "true". So for now, always use that to check

**Comment by kekavc24** [comment]
Ok thanks. Again awesome package. Works flawlessly.
