### ISSUE TITLE
E/flutter (23412): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: NoSuchMethodError: No top-level method 'allowInterop' declared.

### ISSUE THREAD

**Issue by ndenisj** [lazicah/flutterwave_web_client#3]
E[/flutter]() (23412): [ERROR:flutter[/lib/ui/ui_dart_state.cc]()(209)] Unhandled Exception: NoSuchMethodError: No top-level method 'allowInterop' declared.

**Comment by lazicah** [comment]
Please could you provide more information on the error. Like what platform?

**Comment by ndenisj** [comment]
Am using it on Android and IOS

**Comment by lazicah** [comment]
As indicated this is a web only plugin. You can search for a mobile plugin for flutterwave
